### ISSUE TITLE
When am I supposed to initialize the app?

### ISSUE THREAD

**Issue by yandiro** [rmmmp/ember-firebase-service#55]
I am injecting the firebase service in my controller, but I get this:
```
Uncaught FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
```
And the entire app doesn't load.

What am I missing?

Thanks!

**Comment by mikkopaderes** [comment]
Probably you haven't done the [configuration](https://github.com/mikkopaderes/ember-firebase-service#configuration). I haven't tested this service against the latest Firebase v9 as well and with the modular SDK being the way moving forward, I don't think this service is actually needed anymore.

**Comment by yandiro** [comment]
I think I had firebase 9 at that moment. I am using it with firebase 8 and it works. Thanks for the addon and for answering!
